#!/bin/bash

echo "
 ██░ ██  ▄████▄     ▓█████▄  ▒█████  ▄▄▄█████▓
▓██░ ██▒▒██▀ ▀█     ▒██▀ ██▌▒██▒  ██▒▓  ██▒ ▓▒
▒██▀▀██░▒▓█    ▄    ░██   █▌▒██░  ██▒▒ ▓██░ ▒░
░▓█ ░██ ▒▓▓▄ ▄██▒   ░▓█▄   ▌▒██   ██░░ ▓██▓ ░ 
░▓█▒░██▓▒ ▓███▀ ░   ░▒████▓ ░ ████▓▒░  ▒██▒ ░ 
 ▒ ░░▒░▒░ ░▒ ▒  ░    ▒▒▓  ▒ ░ ▒░▒░▒░   ▒ ░░   
 ▒ ░▒░ ░  ░  ▒       ░ ▒  ▒   ░ ▒ ▒░     ░    
 ░  ░░ ░░            ░ ░  ░ ░ ░ ░ ▒    ░      
 ░  ░  ░░ ░            ░        ░ ░           
        ░            ░                        
"

HOME_PREFIX=~/
DOT_PREFIX=~/.hc-dot/dot_files/
declare -a DOT_FILES=(.bashrc .bash_aliases .gitconfig)

# Clone this repository
echo "
-- Cloning the hc-dot repository to ~/.hc-dot
";
git clone https://github.com/horea-chivu/hc-dot.git ~/.hc-dot

# Backup old files that could possibly be replaced
echo "
-- Creating ~/.dot_backup directory
"
if [ ! -d ~/.dot_backup ]; then
    mkdir ~/.dot_backup
fi
echo "
-- Moving your existing files to ~/.dot_backup
-- Creating symbolic links for the dot files
"
for file in ${DOT_FILES[@]}; do
    if [ -e $HOME_PREFIX$file ]; then
        mv $HOME_PREFIX$file ~/.dot_backup
    else
        echo "File does not exist: $file"
    fi
    if [ -e $DOT_PREFIX$file ]; then
        ln -s $DOT_PREFIX$file ~/
    else
        echo "ERROR: File does not exist in ~/.hc-dot: $file"
    fi
done

echo "
-- Sourcing .bashrc file
"
source ~/.bashrc
