#!/bin/bash

HOME_PREFIX=~/
declare -a DOT_FILES=(.bashrc .bash_aliases .gitconfig)

# Remove symbolic files
echo "
-- Removing symbolic links
"
for file in ${DOT_FILES[@]}; do
    if [ -e $HOME_PREFIX$file ]; then
        rm $HOME_PREFIX$file ~/.dot_backup
    else
        echo "File does not exist: $file"
    fi
done

echo "
-- Removing .hc-dot directory
"
sudo rm -R ~/.hc-dot
