#!/bin/bash

sudo add-apt-repository ppa:graphics-drivers/ppa
sudo apt-get update
sudo apt-cache search nvidia-[200-500]

sudo apt-get purge .*nvidia.* bumblebee.* .*primus.*
sudo apt-get --purge autoremove
sudo apt-get install nvidia-375
sudo apt-get install nvidia-settings nvidia-prime
sudo apt-get install nvidia-cuda-toolkit
sudo apt-get install libcupti-dev nvidia-settings nvidia-prime libgl1-mesa-dev nvidia-cuda-doc nvidia-cuda-gdb nvidia-visual-profiler

sudo add-apt-repository ppa:neovim-ppa/stable
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install neovim
sudo apt-get install python-dev python-pip python3-dev python3-pip
sudo pip3 install setuptools
sudo pip3 install --upgrade neovim
